apiVersion: v1
kind: Service
metadata:
  name: tradewisev2-grafana
spec:
  selector:
    app: tradewisev2-grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
  type: NodePort
