spring.application.name=tradewise-v2-backend

server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/tradewisev2db
spring.datasource.username=root
spring.datasource.password=Vaidehi@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
